name: "Icecast"
description: "An icecast2 server with ffmpeg streams hosted"
url: "http://github.com/Kallinski/ha-addons/icecast"
version: "0.1.0"
slug: "icecast"
audio: true
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: mohankumargupta/ha-addon-icecast-{arch}
startup: services
ingress: true
ingress_port: 8099
ingress_stream: true
panel_icon: mdi:radio
ports:
  8000/tcp: 8000
